defaults: &defaults
  per_page: 30000
  number_of_fixtures: 30

development:
  test_var: development
  <<: *defaults
  
test:
  test_var: test
  <<: *defaults

production:
  test_var: production
  <<: *defaults
