defaults: &defaults
  per_page: 30
  number_of_fixtures: 500

development:
  test_var: development
  <<: *defaults
  
test:
  test_var: test
  <<: *defaults

production:
  test_var: production
  <<: *defaults
